### ISSUE TITLE
Flipper BFFB microSD [also GPS and BLE glichy] is not recognised/unavailable!

### ISSUE THREAD

**Issue by byFynn** [Spooks4576/Ghost_ESP#117]
On the "Big F**king Flipper Board" is a microSD slot wich is currently not working/recognised with the Ghost ESP firmware. I tested this with a lot of different SD cards and also different formats but it still wont upload anything from the web ui. The GPS and BLE is also sadly glichy and wont work sometimes. I think this is caused because for the BFFB the only firmware is "esp_generic" so it would be great to have the BFFB officially supported. That would be pretty awesome because a lot of people got that thing and it has a lot of features combined. I also saw you guys are currently working on a wifi pineapple detector/deauther wich is pretty cool! Keep up the great work!

**Comment by Spooks4576** [comment]
i do not have the BFFB to test with however if you would like to make changes / add support yourself considering this is open source feel free to make a PR with the code changes for review 

If this changes in the future and i end up getting a BFFB i will reopen this issue
