### ISSUE TITLE
Merge binaries

### ISSUE THREAD

**Issue by sk9la** [Spooks4576/Ghost_ESP#20]
Hi,

Is it possible to merge all the bins per board for future releases ?

Usually this is what I do when I download a new version of the ghost-esp firmware:
`esptool merge_bin --flash_mode keep --flash_freq keep --flash_size 4MB -o firmware.bin 0x1000 bootloader.bin 0x8000 partition-table.bin 0x10000 Ghost_ESP_IDF.bin`

Then flashing becomes easier: `esptool -c esp32 -p /dev/ttyUSB3 -b 460800 --before default_reset --after hard_reset write_flash 0x0 firmware.bin`

**Comment by Spooks4576** [comment]
I would but then again you only have to flash bootloader and partition table once after that unless you switch firmware's completely you only need to flash the main firmware bin anyway.

that being said I don't really see a point in doing that if you can just flash the firmware bin each update as the bootloader and partition table stay the same with each update always.

**Comment by Spooks4576** [comment]
if I could somehow merge them automatically upon building the project that would be a better solution but until I or someone else figures that out I'm leaving it the way it is 

if you do end up figuring out for me how to merge the bins on build so I don't have to use esp tool all the time then I would be more than happy to just provide the merged bins
