### ISSUE TITLE
When you can add a blue spam with custom Mac id 

### ISSUE THREAD

**Issue by artiomborovinskii** [Spooks4576/Ghost_ESP#23]
I know what a ble spam is wark good for ios device but they block a Mac address for who spam

**Comment by Spooks4576** [comment]
blespam will come when it comes i am currently focusing on screen support at the moment for updates please join the discord linked at the bottom of https://flasher.spookytools.com

**Comment by jaylikesbunda** [comment]
blespam come wen it come, me bizy now on skreen suport only. for updat join discrod link
