### ISSUE TITLE
Issues with CYD 2USB (ESP32-2432S028R) firmware.

### ISSUE THREAD

**Issue by Colonel-Dixie** [Spooks4576/Ghost_ESP#30]
Hello,       

Today I tried the firmware on CYD 2USB SP32-2432S028R, and faced issues. 

I downloaded the firmware https://github.com/Spooks4576/Ghost_ESP/releases/download/VA1.3/Screen_CYD2USB.zip 
I flashed it with https://esp.huhn.me/
Bootloader at 0x1000, partition at 0x8000, and the firmware at 0x10000, and after flashing, nothing at all on screen.      

Then I flashed the M5 launcher from the web flasher https://bmorcelli.github.io/M5Stick-Launcher/flash0.html
Then I installed the Ghost_ESP_IDF.bin within the launcher, and I got an image, but it's flipped, cropped, and the touch doesn't work. 
See attached video please:

https://github.com/user-attachments/assets/4743c152-e7b5-43ae-b0d9-0bdc5ce3b1d9

I also have a CYD variant 3.5" Capacitive [ESP32-3248S035C](https://www.aliexpress.us/item/3256804446638703.html) I can test if you want testers :)       
          
          
Thank you :)          

Edit: I just noticed that you got a webflasher! 
I tried that and still, black screen on the ESP32-2432S028R
<img width="525" alt="{E0C4BFBD-B1FF-4FFC-B037-1DFFD7C171C8}" src="https://github.com/user-attachments/assets/3625dce2-6946-4165-b3d3-ff3f00aa315c">

**Comment by Spooks4576** [comment]
what CYD do you have in specifically 

There are 3 variants im aware of 

- Micro USB (Supported)
- USB C (Supported)
- Micro USB and USB C (Not Supported)

**Comment by Colonel-Dixie** [comment]
Oh, I just noticed that the one I got is not supported, I have one with 2USB, I thought it was supported since the file name is "Screen_CYD2USB.zip" 

![photo_2024-10-28_05-40-20](https://github.com/user-attachments/assets/fc60b601-f0a2-4ec0-8891-682ca6b6d97e)

I will close this issue as it's not a software issue, maybe a file name issue.   
Maybe changing the file name from "Screen_CYD2USB.zip" to "Screen_CYD_USB_C.zip might clear the confusion.     
 
Thanks again, and I hope see this project be ported to other devices too :)

**Comment by Spooks4576** [comment]
yep thank you so much i plan to add support for this CYD variant in November so stay on the look out
