### ISSUE TITLE
CYD not working

### ISSUE THREAD

**Issue by loewal** [Spooks4576/Ghost_ESP#31]
Hi,
I flashed my CYD (usb-c) with the usual offsets.
There's no screen visible.
My fault?

**Comment by loewal** [comment]
Sorry for not reading your post well on Discord!

**Comment by Spooks4576** [comment]
What CYD are you using if it has a micro USB and USB C on it then its not supported 

only CYD's we support is the USB-C variant and the micro USB variant

**Comment by Spooks4576** [comment]
im closing this issue as its not a firmware bug but a board we will support in the future
