### ISSUE TITLE
Add Handshake 

### ISSUE THREAD

**Issue by Ashish393** [Spooks4576/Ghost_ESP#34]
Please added wifi handshake Features

**Comment by Spooks4576** [comment]
can you be more specific

**Comment by Spooks4576** [comment]
closing this as this is not a issue but a suggestion please forward suggestions to the discord https://discord.gg/37W3KWA5

**Comment by Ashish393** [comment]
This is Wifi Password Cracking system.  Already i useing it.
You can see the project.  Link in the blew. 
https://github.com/risinek/esp32-wifi-penetration-tool
