### ISSUE TITLE
ESP CYD2USD

### ISSUE THREAD

**Issue by Grzybekrk** [Spooks4576/Ghost_ESP#35]
Hi 
I have uploaded code to CYD 2 USB but its not working I have uloaded also this another one but screen is flipped and not workig good

**Comment by Spooks4576** [comment]
we only support the USB C and Micro USB Variants of CYD 

we do NOT support the CYD with Micro USB and USB C in one 


Thanks

**Comment by Grzybekrk** [comment]
Are you planning create for this one too??
