### ISSUE TITLE
Touch screen is not working 

### ISSUE THREAD

**Issue by Grzybekrk** [Spooks4576/Ghost_ESP#36]
Hi I have uploaded the ghost on my marauder I used awokandmarauder v6 but my touchscreen is not working any idea why ![20241030_143800.jpg](https://github.com/user-attachments/assets/80a59850-2e75-4ea7-ad1f-991be666775e)

**Comment by Spooks4576** [comment]
touch screen should work which version did you flash from release?

**Comment by Grzybekrk** [comment]
It was 1.3

**Comment by Spooks4576** [comment]
really depends what touch screen driver / controller your using / needing if your not using a XT i believe it began with touch controller 

than your kinda outta luck 
this also looks like a DIY module which you would need to compile from source if that was the case

**Comment by Spooks4576** [comment]
im closing this issue as its stale please reopen if you have further issues
