### ISSUE TITLE
Uncaught (in promise) Error: No asset pattern found for board type ESP32.

### ISSUE THREAD

**Issue by Supruim** [Spooks4576/Ghost_ESP#37]
i get this error when trying to flash ESP32-WROOM-32D

i followed your tutorial and got this message right after this:

Selected board: ESP32 Serial port opened. Connected to ESP32-D0WDQ6 (revision 1) Erasing flash (this may take a while)... Fetching latest release from GitHub...

console: Uncaught (in promise) Error: No asset pattern found for board type ESP32.

**Comment by Spooks4576** [comment]
web flasher will be fixed soon thanks for bringing this to my attention

**Comment by Spooks4576** [comment]
Fixed please wait for the next release to be ready

**Comment by Supruim** [comment]
works like a charm, quick fix!
