### ISSUE TITLE
Web Flasher issue

### ISSUE THREAD

**Issue by TCPMeta** [Spooks4576/Ghost_ESP#38]
Tried three different ESP32-C3 boards and two different computers. T
ried the Spacehuhn web flasher but ran into an issue with that so I tried your web flasher and it gets to Fetching latest release from GitHub... then just sits there.

![IMG_20241030_190158_736](https://github.com/user-attachments/assets/33e15ac7-2412-44d4-b17b-88acf751927f)

**Comment by Spooks4576** [comment]
this will be fixed soon thanks for bringing that to my attention

**Comment by Spooks4576** [comment]
Fixed please wait for the next release to be ready
