### ISSUE TITLE
Can't use WifI

### ISSUE THREAD

**Issue by Alex9532** [Spooks4576/Ghost_ESP#41]
I set the wifi password, and now it won't let me connect. I tried resetting the ESP, but it didn't work. Any ideas?

**Comment by Spooks4576** [comment]
what exactly did you set? if its the wifi password for the access point you cant without erasing your board and reflashing 

if its just for your wifi then just restart the board

**Comment by Alex9532** [comment]
It is the EAP password, and I already tried reflaeshing

**Comment by Spooks4576** [comment]
best bet i can give you is to reflash your board with a different firmware which will clear the nvs cache and then reflash mine

**Comment by Spooks4576** [comment]
Closing this as its stale
