### ISSUE TITLE
Cardputer not starting

### ISSUE THREAD

**Issue by loewal** [Spooks4576/Ghost_ESP#43]
Hi,

I wonder why my previous issue has disappeared...
v.1.3 worked fine by copying OTA main bin and starting with M5Launcher
v.1.3.5 comes with black screen.

Any ideas?

**Comment by loewal** [comment]
I see, you're busy....reverting...?

**Comment by jaylikesbunda** [comment]
> I see, you're busy....reverting...?

it's called development
