### ISSUE TITLE
Guition Display Support

### ISSUE THREAD

**Issue by mmilleror** [Spooks4576/Ghost_ESP#63]
I was wondering if you could add support for the Guition JC4827W543? I was able to load Ghost ESP on it.  The web server works. 
https://www.aliexpress.us/item/3256806543342794.html?gatewayAdapt=glo2usa

It has a U.FL connector on the ESP32. 

Thanks

**Comment by Spooks4576** [comment]
will look into it thank you for bringing this to my attention

**Comment by Spooks4576** [comment]
so after 

> I was wondering if you could add support for the Guition JC4827W543? I was able to load Ghost ESP on it. The web server works. https://www.aliexpress.us/item/3256806543342794.html?gatewayAdapt=glo2usa
> 
> It has a U.FL connector on the ESP32.
> 
> Thanks

so after looking into this I can definitely try and do it but your going to need to add me on discord so we can debug back and forth easier as github issues is not the place for this 

please join the discord server linked in the flasher site on this github and feel free to ping me with your board type so i know who you are thanks

**Comment by mmilleror** [comment]
Happy to help with debugging the board. I went you a friend request with a username with 907 in it.  I can't join the discord for some reason via the discord app.  I can on my phone.

**Comment by mmilleror** [comment]
done.

**Comment by Spooks4576** [comment]
> done.

please make a help form on the discord so we can continue discussion about support there im going to close this issue as github issues is not the place for board support requests
