### ISSUE TITLE
2usc TC screen error

### ISSUE THREAD

**Issue by Pro123123kk** [Spooks4576/Ghost_ESP#69]
The cYD version and the remaining versions have screen errors
![IMG_1667](https://github.com/user-attachments/assets/bfa8d969-8821-485f-ad46-dccce8a8f2b5)
![IMG_1666](https://github.com/user-attachments/assets/a6c32632-ef78-419c-ad2d-b9b58fb43a00)
![IMG_1665](https://github.com/user-attachments/assets/a26717f3-a9a8-48b0-bf50-f4f0e6b41fc2)
![IMG_1664](https://github.com/user-attachments/assets/c1ae5f9e-6d54-401a-a75b-dd19fbdfd6e1)
![image](https://github.com/user-attachments/assets/f73ceacb-b954-44f6-9c32-3b7ffa81d4f1)

**Comment by Spooks4576** [comment]
just fixed the issue and updated bins on github and the flasher site for that varient please reflash 

please let me know if its fixed so i can close this issue

**Comment by Pro123123kk** [comment]
It's been fixed, but running wifi and attack is not very good

**Comment by Pro123123kk** [comment]
It's not completely finished yet, it's just beautiful and functional

**Comment by Spooks4576** [comment]
> It's been fixed, but running wifi and attack is not very good

i recommend you flash again as i pushed a emergency update that fixes bluetooth and terminal view logs 

i will close this as the original issue is fixed please feel free to open a new issue if you encounter anything else

**Comment by Pro123123kk** [comment]
Okay thank you for your help have a wonderful day
