### ISSUE TITLE
ESP32 MARAUDER v6

### ISSUE THREAD

**Issue by zloneotm** [Spooks4576/Ghost_ESP#87]
The compatibility is amazing! 
I see that it is "under development" for the tft 2.8 display. Whenever I run commands on my marauder v6, I am not able to see live feed of data, just an empty terminal. 
Can anyone duplicate this to ensure it's the display development?

**Comment by Spooks4576** [comment]
> The compatibility is amazing! I see that it is "under development" for the tft 2.8 display. Whenever I run commands on my marauder v6, I am not able to see live feed of data, just an empty terminal. Can anyone duplicate this to ensure it's the display development?

most of the commands right now in terms of the display support with terminal logs indeed do not log anything yet 
despite the commands themselves are actually working ive gone through about half of the commands to make sure they log to the terminal but not all commands in the wifi section might log or give feedback despite it actually doing something in the background 

im going to continue to implement the rest of the logs to the terminal view next release 

thanks again
