### ISSUE TITLE
how select all? 

### ISSUE THREAD

**Issue by MrVINIK** [Spooks4576/Ghost_ESP#88]
how select all elements with target?
Tried: select -a all
not working. Extremely inconvenient

**Comment by Spooks4576** [comment]
just dont run the select command? if you dont make a select option it does everything by default

**Comment by Spooks4576** [comment]
not only that but i dont know where you got select -a all from when it is not listed in the commands anywhere if your wanting to select all access points just dont run the select command at all thank you
