### ISSUE TITLE
Not Operating

### ISSUE THREAD

**Issue by DefinetlyNotAI** [Spooks4576/Ghost_ESP#9]
**Describe the bug**

**To Reproduce**

1. Go to the upload (use the firmware for version ESP32_V5)
2. Used PuTTY to connect (COM4, baud rate 14400)
3. See error:
`
rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
wrong chip id 0x0002
`
`
ets Jul 29 2019 12:21:46
`

**Expected behavior**
the default console should be available

**Screenshots**
no need

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera GX
 - Version ...

**Additional context**
nope

**Comment by Spooks4576** [comment]
Your Using the ESP32_V5 From Awok boards correct?

do you know exactly which ESP-32 your board has?

**Comment by DefinetlyNotAI** [comment]
Oh, um... I am using the ESP32-WROOM board, as well as the dev board for the flipper, both do not work, i expect that for the wroom, but not the flippers esp32 board

**Comment by Spooks4576** [comment]
Your Flipper Dev Board Should Work with 

https://github.com/Spooks4576/Ghost_ESP/releases/download/V1.4.6/flipper_dev_board.tar.gz

make sure you are flashing it correctly with the right offsets stated in the README

**Comment by DefinetlyNotAI** [comment]
Ok now it works, what about the esp32 wroom?

**Comment by Spooks4576** [comment]
depending on your board you could flash the minion marauder which uses the esp32 wroom

**Comment by DefinetlyNotAI** [comment]
ok thanks
