### ISSUE TITLE
Flipper Hub Ultimate board Touchscreen issue

### ISSUE THREAD

**Issue by Chaoscake** [Spooks4576/Ghost_ESP#91]
Hey again.
Updated the Flipper Hub Ultimate board with the spookytools flasher.
Touchscreen has no function. 
Flashed marauder on it to confirm functionality of the screen. Hardware is ok, Touchscreen works.
Flashed GhostESP 1.4.2 and 1.4.3 on it. 
Touchscreen with bot fw without function.

**Comment by Spooks4576** [comment]
> Hey again. Updated the Flipper Hub Ultimate board with the spookytools flasher. Touchscreen has no function. Flashed marauder on it to confirm functionality of the screen. Hardware is ok, Touchscreen works. Flashed GhostESP 1.4.2 and 1.4.3 on it. Touchscreen with bot fw without function.

it should work as i verified it worked on 1.4.2 can you give me more details

**Comment by Chaoscake** [comment]
I flashed as suggested with your flasher. FlipperHub, blue port, flashed successfully. Touchscreen doesn't work. Flashed Marauder with FZEE on it, Touchscreen works. Tried launching WebUi. I remembered it showing V 1.4.1 before, but now I cant even get the WebUi to show up.
I don't know what I'm doing wrong

**Comment by Spooks4576** [comment]
> I flashed as suggested with your flasher. FlipperHub, blue port, flashed successfully. Touchscreen doesn't work. Flashed Marauder with FZEE on it, Touchscreen works. Tried launching WebUi. I remembered it showing V 1.4.1 before, but now I cant even get the WebUi to show up. I don't know what I'm doing wrong

id recommend you showing me some logs of you attempting to use it through the serial terminal as that will give me more insight of what is happening

**Comment by Chaoscake** [comment]
[serial_logs.txt](https://github.com/user-attachments/files/17836796/serial_logs.txt)

Added logs... hope I did it right

**Comment by Chaoscake** [comment]
SD card rendered fake touch input due to bord layout. SD card removed and Touchscreen worked. 
Unser error.
Thanks for the help though
