### ISSUE TITLE
CYD Dual USB

### ISSUE THREAD

**Issue by mxrxtr** [Spooks4576/Ghost_ESP#96]
Touch Controls are horribel
How to select things
How to scroll

**Comment by Spooks4576** [comment]
you dont scroll the screen is divided into 3 halfs top of the screen is to go up bottom of the screen is to go down 
middle screen to select and go back depending on what menu you are in 

this is not a issue but more so a misunderstanding of how the touch controls works which is also stated in the wiki 

thank you for your understanding
